import { spawn } from 'child_process';
import { createRequire } from 'module';
import { builtinModules } from 'module';
import process from 'process';

const require = createRequire(import.meta.url);
const prod = (process.argv[2] === "production");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// 定位 esbuild 平台二进制并直接 spawn（stdio inherit）。
// 相比 esbuild JS API，这种方式在受限/沙箱环境下也能派生原生进程。
import * as path from 'path';

const platformPkg = `@esbuild/${process.platform}-${process.arch}`;
let binary;
try {
    const pkgRoot = path.dirname(require.resolve(`${platformPkg}/package.json`));
    binary = path.join(pkgRoot, process.platform === 'win32' ? 'esbuild.exe' : 'bin/esbuild');
} catch {
    binary = require.resolve('esbuild/bin/esbuild');
}

const common = [
    "src/main.ts",
    "--bundle",
    "--format=cjs",
    "--target=es2018",
    "--log-level=info",
    "--banner:js=" + banner.trim(),
    "--external:obsidian",
    "--external:electron",
    "--external:@codemirror/*",
    "--external:lezer",
    "--external:@lezer/*",
    "--external:codemirror",
    "--external:moment",
    ...builtinModules.map((m) => `--external:${m}`),
    "--outfile=main.js",
];

if (prod) {
    common.push("--minify");
} else {
    common.push("--sourcemap=inline");
    common.push("--watch");
}

const child = spawn(binary, common, { stdio: "inherit" });
child.on("error", (err) => {
    console.error("esbuild spawn failed:", err);
    process.exit(1);
});
child.on("exit", (code) => process.exit(code ?? 1));
